from assets.model import TrainerModel
import json
import os

model = TrainerModel()
array = [
    "how to reverse a list in python",
    "python read csv file example",
    "python json parse",
    "python requests get example",
    "python list comprehension",
    "python exception handling try except",
    "python class inheritance",
    "python decorators",
    "python lambda function",
    "python map filter reduce",
    "python threading example",
    "python regex match",
    "python datetime format",
    "python file read write",
    "python os path join",
    "python virtualenv create",
    "python pip install requirements",
    "python flask hello world",
    "python django model example",
    "python sqlite3 select",
    "python pandas dataframe",
    "python numpy array",
    "python matplotlib plot",
    "python scikit learn linear regression",
    "python tensorflow basic",
    "python async await example",
    "python websocket client",
    "python socket programming",
    "python logging config",
    "python unittest example",
    "how to add a list into another list in python?",
    "javascript array map example",
    "javascript fetch api get",
    "javascript promises async await",
    "javascript dom manipulation",
    "javascript event listener",
    "javascript object destructuring",
    "javascript arrow functions",
    "javascript class constructor",
    "javascript localstorage set get",
    "javascript json stringify parse",
    "javascript settimeout setinterval",
    "javascript filter reduce",
    "javascript spread operator",
    "javascript template literals",
    "javascript module export import",
    "javascript error handling try catch",
    "javascript closure example",
    "javascript hoisting",
    "javascript event loop",
    "javascript callback hell",
    "html center div",
    "css flexbox tutorial",
    "css grid layout",
    "html form input types",
    "css media queries responsive",
    "html table example",
    "css animations keyframes",
    "html div span difference",
    "css position absolute relative",
    "html semantic elements",
    "css box model",
    "html canvas draw",
    "html video audio tags",
    "css variables custom properties",
    "html doctype meta tags",
    "css pseudo classes selectors",
    "html bootstrap grid",
    "css transition transform",
    "html iframe embed",
    "css z-index stacking",
    "html link script tags",
    "sql select join example",
    "sql group by having",
    "sql insert into select",
    "sql update delete",
    "sql create table primary key",
    "sql foreign key constraint",
    "sql index performance",
    "sql subquery exists",
    "sql distinct count",
    "sql order by limit",
    "sql like wildcard",
    "sql case when statement",
    "sql union intersect except",
    "sql date functions",
    "sql aggregate functions",
    "sql stored procedure",
    "sql trigger example",
    "sql view create",
    "sql transaction commit rollback",
    "sql window functions rank",
    "git merge vs rebase",
    "git clone branch",
    "git commit amend",
    "git push force",
    "git pull fetch",
    "git stash apply",
    "git reset hard soft",
    "git cherry-pick",
    "git rebase interactive",
    "git log pretty",
    "git remote add",
    "git tag create",
    "dockerfile example",
    "docker build run",
    "docker compose up",
    "docker volume mount",
    "docker network bridge",
    "docker image rm",
    "docker container logs",
    "docker exec bash",
    "docker pull push",
    "docker registry private",
    "linux grep command examples",
    "linux find exec",
    "linux awk sed",
    "linux chmod chown",
    "linux ps kill",
    "linux netstat ss",
    "linux curl wget",
    "linux tar gzip",
    "linux cron job",
    "linux ssh keygen",
    "linux scp rsync",
    "linux alias bashrc",
    "linux top htop",
    "linux df du",
    "linux iptables firewall",
    "linux systemctl service",
    "linux journalctl logs",
    "linux useradd usermod",
    "linux mount fstab",
    "linux ping traceroute",
    "linux nmap netcat",

    "python type hints mypy example",
    "python dataclasses vs pydantic",
    "python context manager with statement",
    "python generator yield next",
    "python asyncio gather tasks",
    "python aiohttp client session",
    "python pytest fixture mock",
    "python property decorator getter setter",
    "python enum example",
    "python functools lru_cache",
    "python logging handler formatter",
    "python argparse command line",
    "python shutil copy move",
    "python subprocess run pipe",
    "python multiprocessing pool map",
    "python pickle load dump",
    "python zipfile extract",
    "python pathlib example",
    "python random choice shuffle",
    "python collections defaultdict counter",
    "python itertools chain cycle",
    "python json custom encoder decoder",
    "python sqlalchemy session query",
    "python fastapi path params",
    "python pydantic model validator",
    "python celery task example",
    "python redis set get",
    "python mongodb pymongo find",
    "python plotly interactive chart",
    "python seaborn heatmap",

    "html dialog modal example",
    "html details summary tag",
    "html picture srcset responsive images",
    "html input datalist autocomplete",
    "html input range slider",
    "html input color picker",
    "html input date min max",
    "html input file multiple accept",
    "html input pattern regex",
    "html contenteditable example",
    "html draggable drag drop",
    "html geolocation api example",
    "html web storage local session",
    "html service worker register",
    "html web workers example",
    "html intersection observer lazy load",
    "html resize observer example",
    "html form validation custom error",
    "html output element example",
    "html meter progress bar",
    "html template tag example",
    "html slot shadow dom",
    "html custom elements define",
    "html inert attribute example",
    "html popover attribute",
    "html view transition api",
    "html loading lazy attribute",
    "html decoding async defer scripts",
    "html preload prefetch",
    "html srcset sizes attribute",

    "css container queries example",
    "css subgrid layout",
    "css logical properties inset inline",
    "css accent-color checkbox radio",
    "css color-scheme dark light",
    "css :has() selector example",
    "css :is :where :not pseudo",
    "css nth-child advanced",
    "css scroll-behavior smooth",
    "css scroll-snap example",
    "css overscroll-behavior",
    "css aspect-ratio property",
    "css object-fit cover contain",
    "css backdrop-filter blur",
    "css mix-blend-mode example",
    "css mask-image clip-path",
    "css shape-outside float",
    "css writing-mode vertical",
    "css column-count multiple",
    "css counter-increment style",
    "css @supports feature query",
    "css @layer cascade layers",
    "css @property custom property",
    "css animation-fill-mode",
    "css perspective transform 3d",
    "css will-change performance",
    "css focus-visible outline",
    "css scrollbar styling webkit",
    "css print media styles",
    "css prefers-color-scheme media",

    "javascript optional chaining ?.",
    "javascript nullish coalescing ??",
    "javascript top-level await example",
    "javascript proxy handler example",
    "javascript reflect api example",
    "javascript weakmap weakset",
    "javascript symbol iterator example",
    "javascript generator function yield*",
    "javascript async generator",
    "javascript for await of loop",
    "javascript promise.allsettled",
    "javascript promise.any race",
    "javascript abortcontroller fetch",
    "javascript broadcastchannel api",
    "javascript share target api",
    "javascript clipboard read write",
    "javascript fullscreen api",
    "javascript vibration api",
    "javascript battery status api",
    "javascript network information",
    "javascript performance measure",
    "javascript intersection observer",
    "javascript mutation observer",
    "javascript resize observer",
    "javascript reporting observer",
    "javascript structured clone",
    "javascript atob btoa example",
    "javascript blob arraybuffer",
    "javascript stream api example",
    "javascript readable stream pipe"
]

for arr in array:
    data = model.process(arr)
    url = []
    stackoverflow_links: list = data["stackoverflow_links"]
    w3school_links = data["w3schools_links"]
    if stackoverflow_links:
        for link in stackoverflow_links:
            url.append(link["link"])

    for link in w3school_links:
        url.append(link["link"])
    model.save(url)
    print(f"Model learned : {arr}")

model.data = json.load(open("data/main.json", "r"))["list"]

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

while True:
    Input = input("Enter your question: ")
    if Input == "cls":
        os.system("cls")
        continue
    res = model.process(Input, json.load(open("data/main.json", "r"))["list"])
    for raw in res["raw_response"]:
        print(raw)