from assets.model import TrainerModel

model = TrainerModel()
array = [
    "how to reverse a list in python",
    "python read csv file example",
    "python json parse",
    "python requests get example",
    "python list comprehension",
    "python exception handling try except",
    "python class inheritance",
    "python decorators",
    "python lambda function",
    "python map filter reduce",
    "python threading example",
    "python regex match",
    "python datetime format",
    "python file read write",
    "python os path join",
    "python virtualenv create",
    "python pip install requirements",
    "python flask hello world",
    "python django model example",
    "python sqlite3 select",
    "python pandas dataframe",
    "python numpy array",
    "python matplotlib plot",
    "python scikit learn linear regression",
    "python tensorflow basic",
    "python async await example",
    "python websocket client",
    "python socket programming",
    "python logging config",
    "python unittest example",
    "javascript array map example",
    "javascript fetch api get",
    "javascript promises async await",
    "javascript dom manipulation",
    "javascript event listener",
    "javascript object destructuring",
    "javascript arrow functions",
    "javascript class constructor",
    "javascript localstorage set get",
    "javascript json stringify parse",
    "javascript settimeout setinterval",
    "javascript filter reduce",
    "javascript spread operator",
    "javascript template literals",
    "javascript module export import",
    "javascript error handling try catch",
    "javascript closure example",
    "javascript hoisting",
    "javascript event loop",
    "javascript callback hell",
    "html center div",
    "css flexbox tutorial",
    "css grid layout",
    "html form input types",
    "css media queries responsive",
    "html table example",
    "css animations keyframes",
    "html div span difference",
    "css position absolute relative",
    "html semantic elements",
    "css box model",
    "html canvas draw",
    "html video audio tags",
    "css variables custom properties",
    "html doctype meta tags",
    "css pseudo classes selectors",
    "html bootstrap grid",
    "css transition transform",
    "html iframe embed",
    "css z-index stacking",
    "html link script tags",
    "sql select join example",
    "sql group by having",
    "sql insert into select",
    "sql update delete",
    "sql create table primary key",
    "sql foreign key constraint",
    "sql index performance",
    "sql subquery exists",
    "sql distinct count",
    "sql order by limit",
    "sql like wildcard",
    "sql case when statement",
    "sql union intersect except",
    "sql date functions",
    "sql aggregate functions",
    "sql stored procedure",
    "sql trigger example",
    "sql view create",
    "sql transaction commit rollback",
    "sql window functions rank",
    "git merge vs rebase",
    "git clone branch",
    "git commit amend",
    "git push force",
    "git pull fetch",
    "git stash apply",
    "git reset hard soft",
    "git cherry-pick",
    "git rebase interactive",
    "git log pretty",
    "git remote add",
    "git tag create",
    "dockerfile example",
    "docker build run",
    "docker compose up",
    "docker volume mount",
    "docker network bridge",
    "docker image rm",
    "docker container logs",
    "docker exec bash",
    "docker pull push",
    "docker registry private",
    "linux grep command examples",
    "linux find exec",
    "linux awk sed",
    "linux chmod chown",
    "linux ps kill",
    "linux netstat ss",
    "linux curl wget",
    "linux tar gzip",
    "linux cron job",
    "linux ssh keygen",
    "linux scp rsync",
    "linux alias bashrc",
    "linux top htop",
    "linux df du",
    "linux iptables firewall",
    "linux systemctl service",
    "linux journalctl logs",
    "linux useradd usermod",
    "linux mount fstab",
    "linux ping traceroute",
    "linux nmap netcat"
]

for arr in array:
    print(f"Model learned : {arr}")
    model.process(arr)
while True:
    Input = input("Enter your question: ")
    print(model.process(Input=Input)["raw_response"])